{% set data = load_setup_py_data() %}
{% set version = environ.get("GIT_DESCRIBE_TAG").lstrip("v") %}

package:
  name: openmdao-scop
  version: "{{ version }}"

about:
  home: https://github.com/ovidner/openmdao-scop
  license: MIT
  license_file: LICENSE

source:
  git_url: ../

build:
  noarch: python
  script: "python -m pip install . --no-deps --ignore-installed -vv "
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python
    - pip
    - setuptools-scm
  run:
    - h5netcdf
    - jsonpickle
    - numpy
    - openmdao<3.17
    - pandas
    - pygmo
    - python
    - xarray

test:
  requires:
    - hypothesis
    - pytest
    - deepdiff
  source_files:
    - tests/
    - pytest.ini
  commands:
    - pytest

extra:
  channels:
    # For conda-lock
    - conda-forge
    - defaults
